---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nacos.io
  resources:
  - configmaps
  - dynamicconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nacos.io
  resources:
  - configmaps/finalizers
  - dynamicconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - nacos.io
  resources:
  - configmaps/status
  - dynamicconfigurations/status
  verbs:
  - get
  - patch
  - update
